### ISSUE TITLE
Request: add a CLI version, callable via `python3 -m tcppinglib <host>:<port>`

### ISSUE THREAD

**Issue by DeflateAwning** [EnginEken/tcppinglib#15]
This library is awesome! It would be so great if there was a CLI version that was callable like `python3 -m tcppinglib <host>:<port>`.

Lots of prominent Python libraries support this sort or use, when a basic CLI tool can be envoked from the core functionality of the library.

**Comment by EnginEken** [comment]
It makes sense to have this functionality. I'll try to implement this. I'm thinking something like below:

usage: tcpping [-h] [-p PORT] [-t TIMEOUT] [-c COUNT] [-i INTERVAL] address

TCP Ping: An Easy Way to Measure the Connectivity and Latency with TCP Ping

positional arguments:
  address               The IP address or FQDN of the host to ping.

options:
  -h, --help            show this help message and exit
  -p PORT, --port PORT  The port number to connect to (default: 80).
  -t TIMEOUT, --timeout TIMEOUT
                        Timeout in seconds for each ping (default: 2).
  -c COUNT, --count COUNT
                        Number of ping requests to send (default: 5).
  -i INTERVAL, --interval INTERVAL
                        Interval in seconds between each ping request (default: 3).

**Comment by EnginEken** [comment]
I've added this functionality with #20. New release will be published later today

**Comment by EnginEken** [comment]
Version 2.0.4 is released. You can now use the cli command as below after upgrading the library to v2.0.4. Please see the [Command Line Interface](https://github.com/EnginEken/tcppinglib?tab=readme-ov-file#command-line-interface-cli) section for usage detail.

```shell
$ tcpping --help
usage: tcpping [-h] [-p PORT] [-t TIMEOUT] [-c COUNT] [-i INTERVAL] address
```

**Comment by DeflateAwning** [comment]
Wow, this is fantastic! Thank you!
