### ISSUE TITLE
Could you please do a release including standard deviation?

### ISSUE THREAD

**Issue by AceSlash** [EnginEken/tcppinglib#19]
Hello,

I was about to implement standard deviation but when I did checkout the code, I noticed that it was already committed.

It looks like that you only need a new release, could you please create one?

And by the way, thank you for this project, it's very useful!

**Comment by EnginEken** [comment]
Hi, 
Thanks for your kind words 

I was thinking to add cli functionality and release it but implementing cli functionality might take some more time. Will try to ship new release in a week
