### ISSUE TITLE
packets_sent, packets_received and packet_loss behaves differently than expected.

### ISSUE THREAD

**Issue by GrigoryIzumov** [EnginEken/tcppinglib#8]
Hi!

I noticed an issue with packets_sent, packets_received and packet_loss statistics which tcpping puts into TCPHost object.
For example, I'm sending request to the nginx server I opened on localhost:8080. After a while, I shutdown the docker image running nginx to simulate packet loss.
```
from tcppinglib import tcpping
host = tcpping(address="localhost", port=8080, timeout=1, count=1000, interval=0.01)
```
Its statistic:
```
------------------------------------------------------------
  127.0.0.1
------------------------------------------------------------
  Packets sent:                    231
  Packets received:                231
  Packet lost:                     769
  Packet loss:                     332.9%
  min/avg/max Round-trip times:    0.094 ms / 0.189 ms / 0.42 ms
------------------------------------------------------------
```
So, its strange to me that packets sent = packets received and packet loss is > 100% :)
It seems more obvious if packets sent = count and packet loss is (count - packet received)/count * 100.

I tried this change locally and got more accurate statistics:
```
------------------------------------------------------------
  127.0.0.1
------------------------------------------------------------
  Packets sent:                    1000
  Packets received:                327
  Packet lost:                     673
  Packet loss:                     67.3%
  min/avg/max Round-trip times:    0.089 ms / 0.185 ms / 0.937 ms
------------------------------------------------------------
```
Is it possible to create a PR for this change? Seems like I don't have permissions to create new branches in this repo.

**Comment by adk23333** [comment]
This author seems very inactive. Perhaps we should create an additional PR branch. And then submit the updates together there.

**Comment by EnginEken** [comment]
Hey @GrigoryIzumov, @adk23333, apologies for the recent inactivity due to personal and work changes. I'm back now and will be reviewing all pending issues and PRs.

**Comment by EnginEken** [comment]
This issue is fixed with [PR#14](https://github.com/EnginEken/tcppinglib/pull/14). I also made another changes on `packets_sent` property of the TCPHost model. `packets_sent` is now set to `count` value to give wholesome stats with TCPHost model.

```
------------------------------------------------------------
  127.0.0.1
------------------------------------------------------------
  Packets sent:                    50
  Packets received:                7
  Packet lost:                     43
  Packet loss:                     86.0%
  min/avg/max Round-trip times:    0.241 ms / 0.517 ms / 0.578 ms
------------------------------------------------------------
```

**Comment by adk23333** [comment]
> Hey @GrigoryIzumov, @adk23333, apologies for the recent inactivity due to personal and work changes. I'm back now and will be reviewing all pending issues and PRs. 

thx, You're back.

**Comment by EnginEken** [comment]
There will be couple of changes. After that library will be updated. Thanks for bringing this issue on sight.

**Comment by adk23333** [comment]
> There will be couple of changes. After that library will be updated. Thanks for bringing this issue on sight.

I think you can rename this module to `aiotcping`. This is more conducive to searching.
