### ISSUE TITLE
namelookuperror cause existed with code=1

### ISSUE THREAD

**Issue by huanweisu** [EnginEken/tcppinglib#9]
I am getting existed if given hostname cannot be resolved
tcppinglib.exceptions.NameLookupError: Given hostname 'qqwddqweqe.eqewqeqwe.com' cannot be resolved

**Comment by EnginEken** [comment]
First thing that this library does is to try to resolve the given address. It can not ping the destination if it can't resolve the name. What is the issue here? Can you explain a bit more?

**Comment by EnginEken** [comment]
Closing
